-- TABLA FORO RELACION USUARIO
ALTER TABLE `proyectolibres`.`foro` 
ADD COLUMN `IDAUTORFORO` INT(11) NULL AFTER `DESCRIPCIONFORO`,
ADD COLUMN `NOMBREAUTORFORO` VARCHAR(60) NULL AFTER `IDAUTORFORO`,
ADD INDEX `fk_foro_usuario_idx` (`IDAUTORFORO`) ;
;
ALTER TABLE `proyectolibres`.`foro` 
ADD CONSTRAINT `fk_foro_usuario`
  FOREIGN KEY (`IDAUTORFORO`)
  REFERENCES `proyectolibres`.`usuario` (`IDUSUARIO`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;